logging:
  pattern:
    dateformat: MM-dd HH:mm:ss:SSS
spring:
  rabbitmq:
    host: 192.168.66.133
    port: 5672 #端口
    username: root
    password: 123456
    virtual-host: /
    listener:
      simple:
        prefetch: 1